geopulse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'placeholder_account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'placeholder_user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'placeholder_password') }}"
      role: "ACCOUNTADMIN"
      database: "GEOPULSE_DB"
      warehouse: "GEOPULSE_WH"
      schema: "dbt_raisa"
      threads: 4
      client_session_keep_alive: False